eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1112/eureka
server:
  port: 1111
spring:
  application:
    name: eureka-server